title: Weikun Wang's Homepage
page-top-title: Weikun Wang
top-section-bg-text: Daß du untergehst, wenn du dich nicht wehrst. Das wirst du doch einsehn.
home-subtitle: Weikun Wang&ensp;|&ensp;王伟坤
copyright-text: '&copy; Weikun Wang 2026-2030. All Rights Reserved.'
